<?php

/**
 * Implements hook_permission().
 */
function mailchimp_campaign_permission() {
  return array(
    'send mailchimp campaign' => array(
      'title' => t('Send MailChimp campaigns'),
      'description' => t('Create and send MailChimp campaigns form nodes.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function mailchimp_campaign_menu() {
  $items['admin/config/services/mailchimp/campaigns'] = array(
    'title' => 'Campaign settings',
    'description' => 'Manage sitewide default MailChimp Campaigns settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailchimp_campaign_admin_form'),
    'access arguments' => array('administer mailchimp'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'mailchimp_campaign.admin.inc',
    'weight' => 10
  );
  $items['node/%node/mailchimp-campaigns'] = array(
    'title' => 'MailChimp campaigns',
    'page callback' => 'mailchimp_campaign_node_campaigns_page',
    'page arguments' => array(1),
    'access callback' => 'mailchimp_campaign_node_campaigns_access',
    'access arguments' => array(1, 'send mailchimp campaign'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['node/%node/mailchimp-campaigns/create'] = array(
    'title' => 'Create new campaign',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailchimp_campaign_create_form', 1),
    'access callback' => 'mailchimp_campaign_node_campaigns_access',
    'access arguments' => array(1, 'send mailchimp campaign'),
    'type' => MENU_LOCAL_ACTION,
  );
  $items['mailchimp-campaign/%mailchimp_campaign/update/%'] = array(
    'title' => 'Update',
    'page callback' => 'mailchimp_campaign_menu_operations',
    'page arguments' => array(1, 2),
    'access callback' => 'mailchimp_campaign_menu_operations_access',
    'access arguments' => array(3, 'send mailchimp campaign'),
    'type' => MENU_CALLBACK,
  );
  $items['mailchimp-campaign/%mailchimp_campaign/send/%'] = array(
    'title' => 'Send',
    'page callback' => 'mailchimp_campaign_menu_operations',
    'page arguments' => array(1, 2),
    'access callback' => 'mailchimp_campaign_menu_operations_access',
    'access arguments' => array(3, 'send mailchimp campaign'),
    'type' => MENU_CALLBACK,
  );
  $items['mailchimp-campaign/%mailchimp_campaign/delete/%'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailchimp_campaign_delete_form', 1),
    'access callback' => 'mailchimp_campaign_menu_operations_access',
    'access arguments' => array(3, 'administer mailchimp'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function mailchimp_campaign_load($cid) {
  return db_select('mailchimp_campaign_node_campaigns', 'm')
    ->fields('m')
    ->condition('cid', $cid)
    ->execute()
    ->fetchAssoc();
}

/**
 * Access callback for node campaigns.
 */
function mailchimp_campaign_node_campaigns_access($node, $permission) {
  if (user_access($permission)) {
    $settings = variable_get('mailchimp_campaign_node_type_settings_' . $node->type, FALSE);
    if ($settings && $settings['enabled']) {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Access callback for menu operations.
 */
function mailchimp_campaign_menu_operations_access($token, $permission) {
  if (drupal_valid_token($token, 'mailchimp_campaign') && user_access($permission)) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Call update or send operations, then returns to the destination.
 */
function mailchimp_campaign_menu_operations($campaign, $op) {
  switch ($op) {
    case 'update':
        mailchimp_campaign_update_campaign($campaign['cid']);
      break;
    case 'send':
        mailchimp_campaign_send($campaign['cid']);
      break;
  }

  $destination = drupal_get_destination();
  // If no given destination, drupal_get_destination() returns with $_GET['q'].
  if ($destination['destination'] != $_GET['q']) {
    $destination = $destination['destination'];
  }
  // Define new destination to avoid infinite loop.
  else {
    $destination = 'node/' . $campaign['nid'] . '/mailchimp-campaigns';
  }

  drupal_goto($destination);
}

/**
 * Implements hook_theme().
 */
function mailchimp_campaign_theme($existing, $type, $theme, $path) {
  return array(
    'mailchimp_campaign_node_campaigns_list' => array(
      'variables' => array('node_campaigns' => array()),
    ),
    'mailchimp_campaign_mclinks' => array(
      'variables' => array('data' => NULL),
    ),
    'mailchimp_campaign_actions' => array(
      'variables' => array('cid' => NULL, 'data' => NULL),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 * MailChimp Campaign module settings on node type edit form.
 */
function mailchimp_campaign_form_node_type_form_alter(&$form, $form_state) {
  module_load_include('inc', 'mailchimp_campaign', 'mailchimp_campaign.settings');
  $defaults = variable_get('mailchimp_campaign_node_type_settings_' . $form['#node_type']->type, FALSE);

  $form['mailchimp_campaign'] = array(
    '#type' => 'fieldset',
    '#title' => t('MailChimp campaign'),
    '#group' => 'additional_settings',
    '#tree' => TRUE,
  );
  $form['mailchimp_campaign']['enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable MailChimp campaigns'),
    '#default_value' => $defaults ? $defaults['enabled'] : FALSE,
  );
  mailchimp_campaign_settings_form(&$form, $defaults);
  $form['mailchimp_campaign']['list_id']['#required'] = FALSE;
  // Hide options if MailChimp Campaigns is not enabled for node type.
  $form['mailchimp_campaign']['list_id']['#states']['visible'][':input[name="mailchimp_campaign[enabled]"]']['checked'] = TRUE;
  $form['mailchimp_campaign']['from_name']['#states']['visible'][':input[name="mailchimp_campaign[enabled]"]']['checked'] = TRUE;
  $form['mailchimp_campaign']['from_email']['#states']['visible'][':input[name="mailchimp_campaign[enabled]"]']['checked'] = TRUE;
  $form['mailchimp_campaign']['template_id']['#states']['visible'][':input[name="mailchimp_campaign[enabled]"]']['checked'] = TRUE;
  $form['mailchimp_campaign']['title_section']['#states']['visible'][':input[name="mailchimp_campaign[enabled]"]']['checked'] = TRUE;
  $form['mailchimp_campaign']['body_section']['#states']['visible'][':input[name="mailchimp_campaign[enabled]"]']['checked'] = TRUE;

  $form['#validate'][] = 'mailchimp_campaign_form_node_type_form_validate';
  $form['#submit'][] = 'mailchimp_campaign_form_node_type_form_submit';
}

/**
 * Validate MailChimp settings on node type edit form.
 */
function mailchimp_campaign_form_node_type_form_validate($form, &$form_state) {
  module_load_include('inc', 'mailchimp_campaign', 'mailchimp_campaign.settings');
  $form_state['defaults'] = variable_get('mailchimp_campaign', FALSE);

  $values = $form_state['values']['mailchimp_campaign'];
  if ($values['enabled'] && !$values['list_id']) {
    form_set_error('mailchimp_campaign][list_id', t('List field is required, if MailChimp campaigns are enabled.'));
  }
  mailchimp_campaign_settings_form_validate($form, &$form_state);
}

/**
 * Save node type settings.
 */
function mailchimp_campaign_form_node_type_form_submit($form, &$form_state) {
  variable_set('mailchimp_campaign_node_type_settings_' . $form_state['values']['type'], $form_state['values']['mailchimp_campaign']);
  variable_del('mailchimp_campaign_' . $form_state['values']['type']);
}

/**
 * Implements hook_entity_info_alter().
 */
function mailchimp_campaign_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['mailchimp_campaign'] = array(
    'label' => t('MailChimp campaign'),
    'custom settings' => FALSE,
  );
}

/**
 * Returns campaigns list. (Associative array for drupal_render()).
 */
function mailchimp_campaign_node_campaigns_page($node) {
  $result = db_select('mailchimp_campaign_node_campaigns', 'm')
    ->fields('m')
    ->condition('nid', $node->nid)
    ->orderBy('update_time', 'DESC')
    ->execute();

  $node_campaigns = array();
  while ($row = $result->fetchAssoc()) {
    if ($row['data']) {
      $row['data'] = unserialize($row['data']);
    }
    $node_campaigns[$row['cid']] = $row;
  }

  $content['title'] = array(
    '#markup' => '<h2>' . t('MailChimp campaigns for %title', array('%title' => $node->title)) . '</h2>',
  );

  $content['campaign_list'] = array(
    '#theme' => 'mailchimp_campaign_node_campaigns_list',
    '#node_campaigns' => $node_campaigns,
  );

  return $content;
}

/**
 * Returns a list with the campaigns of a node.
 */
function theme_mailchimp_campaign_node_campaigns_list($variables) {
  $node_campaigns = $variables['node_campaigns'];
  $header = array(t('ID'), t('Title'), t('List'), t('Status'), t('MC links'), t('Last updated'), t('Actions'));

  foreach ($node_campaigns as $cid => $campaign) {
    $row = array();
    $row[] = $cid; // ID
    if ($campaign['data']) {
      $row[] = check_plain($campaign['data']['title']); // Title
      $row[] = _mailchimp_campaign_list_name($campaign['data']['list_id']); // List
      $row[] = check_plain($campaign['data']['status']); // Status
      $row[] = theme('mailchimp_campaign_mclinks', array('data' => $campaign['data'])); // MC links
    }
    else {
      $row[] = array(
        'data' => '<em>' . t('No available information, please update.') . '</em>',
        'colspan' => '4',
      );
    }
    $row[] = format_date($campaign['update_time']); // Last updated
    $row[] = theme('mailchimp_campaign_actions', array('cid' => $campaign['cid'], 'data' => $campaign['data'])); // Actions

    $rows[] = $row;
  }

  return theme('table', array('header' => $header, 'rows' => $rows));
}

/**
 * Returns MC links as item list.
 */
function theme_mailchimp_campaign_mclinks($variables) {
  $data = $variables['data'];

  $items = array();
  $items[] = _mailchimp_campaign_mailchimp_admin_link(t('Edit'), 'campaigns/show', $data['web_id']);
  $items[] = l('Web archive page', $data['archive_url'], array('attributes' => array('target' => '_blank')));
  if (in_array($data['status'], array('sending', 'sent'))) {
    $items[] = _mailchimp_campaign_mailchimp_admin_link(t('Reports'), 'reports/summary', $data['web_id']);
  }

  return theme('item_list', array('items' => $items));
}

/**
 * Returns action (update/send) links.
 */
function theme_mailchimp_campaign_actions($variables) {
  $data = $variables['data'];
  $cid = $variables['cid'];

  $items = array();
  if (user_access('administer mailchimp')) {
    $items[] = l(t('Delete'), 'mailchimp-campaign/' . $cid . '/delete/' . drupal_get_token('mailchimp_campaign'));
  }
  $items[] = l(t('Update'), 'mailchimp-campaign/' . $cid . '/update/' . drupal_get_token('mailchimp_campaign'));
  if ($data['status'] == 'save') {
    $items[] = l(t('Send'), 'mailchimp-campaign/' . $cid . '/send/' . drupal_get_token('mailchimp_campaign'));
  }

  return theme('item_list', array('items' => $items));
}

/**
 * Form for create MailChimp campaign, from node content.
 */
function mailchimp_campaign_create_form($form, &$form_state) {
  module_load_include('inc', 'mailchimp_campaign', 'mailchimp_campaign.settings');
  $node = $form_state['build_info']['args'][0];
  $defaults = variable_get('mailchimp_campaign_node_type_settings_' . $node->type, FALSE);

  $form = array();
  $form['mailchimp_campaign_preview'] = array(
   '#type' => 'fieldset',
   '#title' => t('Campaign content preview'),
   '#collapsible' => TRUE,
   '#collapsed' => TRUE,
  );
  $form['mailchimp_campaign_preview']['preview'] = array(
    '#type' => 'item',
    '#title' => check_plain($node->title),
    '#markup' => _mailchimp_campaign_body($node),
  );
  $form['mailchimp_campaign'] = array(
    '#type' => 'fieldset',
    '#title' => t('Create new MailChimp campaign'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
  );
  $form['mailchimp_campaign']['subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Mail subject'),
    '#default_value' =>  $node->title . ' - ' . variable_get('site_name', FALSE),
    '#required' => TRUE,
  );
  $form['mailchimp_campaign']['campaign_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Campaign title'),
    '#default_value' => $node->title,
    '#required' => TRUE,
  );
  if (user_access('administer mailchimp')) {
    mailchimp_campaign_settings_form(&$form, $defaults);
  }
  $form['mailchimp_campaign']['create'] = array(
    '#type' => 'submit',
    '#value' => t('Create new campaign from node'),
  );

  return $form;
}

/**
 * Validate MailChimp campaign creation form.
 */
function mailchimp_campaign_create_form_validate($form, &$form_state) {
  module_load_include('inc', 'mailchimp_campaign', 'mailchimp_campaign.settings');
  $node = $form_state['build_info']['args'][0];
  $form_state['defaults'] = variable_get('mailchimp_campaign_node_type_settings_' . $node->type, FALSE);

  mailchimp_campaign_settings_form_validate($form, &$form_state);
}

/**
 * Create MailChimp campaign on form submission.
 */
function mailchimp_campaign_create_form_submit($form, $form_state) {
  if (isset($form_state['build_info']['args'][0]->nid)) {
    $node = $form_state['build_info']['args'][0];
    mailchimp_campaign_create($node, $form_state['values']['mailchimp_campaign']);
  }
}

/**
 * Form for delete a campaign form the database and/or MailChimp.
 */
function mailchimp_campaign_delete_form($form, &$form_state) {
  $campaign = $form_state['build_info']['args'][0];
  $campaign['data'] = unserialize($campaign['data']);
  $admin_link = _mailchimp_campaign_mailchimp_admin_link(t('Campaign admin page'), 'campaigns/show', $campaign['data']['web_id']);

  $form['info'] = array('#markup' => '<p>Campaign ID: <em>' . $campaign['cid'] . '</em><br />'. $admin_link . '</p>');
  $form['delete_from'] = array(
    '#type' => 'radios',
    '#title' => t('Delete campaign'),
    '#options' => array(
      'db' => t('Only from site database'),
      'mc' => t('From site database and from MailChimp'),
    ),
    '#default_value' => 'db',
  );

  return confirm_form($form, t('Are you sure you want to delete this campaign: %id', array('%id' => $campaign['data']['title'])), 'node/' . $campaign['nid']. '/mailchimp-campaigns');
}

/**
 * Delete a campaign from the database on form submit.
 */
function mailchimp_campaign_delete_form_submit($form, &$form_state) {
  $campaign = $form_state['build_info']['args'][0];
  if ($form_state['values']['delete_from'] == 'mc') {
    mailchimp_campaign_delete_campaign($campaign['cid']);
  }
  else {
    _mailchimp_campaign_delete_form_database($campaign['cid']);
  }
}

/**
 * Create MailChimp campaign from a node.
 */
function mailchimp_campaign_create($node, $settings) {
  global $base_url;
  $mcapi = mailchimp_get_api_object();
  $type = 'regular';
  $options = array(
    'list_id' => $settings['list_id'],
    'subject' => $settings['subject'],
    'from_email' => $settings['from_email'],
    'from_name' => $settings['from_name'],
    'title' => $settings['campaign_title'],
    'template_id' => $settings['template_id'],
    'generate_text' => TRUE,
    'tracking' => array(
      'opens' => TRUE,
      'html_clicks' => TRUE,
      'text_clicks' => TRUE,
    ),
  );
  $body = _mailchimp_campaign_body($node);
  $title = l($node->title, 'node/' . $node->nid, array('absolute' => TRUE));
  $content = array();
  if ($settings['title_section'] == $settings['body_section']) {
    $content['html_' . $settings['body_section']] = '<h1>' . $title . '</h1>' . $body;
  }
  else {
    $content['html_' . $settings['title_section']] = $title;
    $content['html_' . $settings['body_section']] = $body;
  }

  // Create campaign on MailChimp.
  $cid = $mcapi->campaignCreate($type, $options, $content);

  if ($mcapi->errorCode) {
    // Display and log error, if any.
    $message = t('MailChimp error. The campaign was not created.') . ' ' . _mailchimp_campaign_mcapi_error_message($mcapi);

    drupal_set_message($message, 'error');
    watchdog('mailchimp_campaign', $message, array(), WATCHDOG_ERROR);
  }
  else {
    // Write campaign details to the database.
    $record = array();
    // Request all campaign datas from MailChimp.
    $record = mailchimp_campaign_update_campaign($cid, FALSE);
    $record['nid'] = $node->nid;
    $record['vid'] = $node->vid;
    drupal_write_record('mailchimp_campaign_node_campaigns', $record);

    $message = t('Campaign was created! (ID: <em>!cid</em>)', array('!cid' => $cid));

    drupal_set_message($message);
    watchdog('mailchimp_campaign', $message);
  }
}

/**
 * Update campaign datas in the database.
 */
function mailchimp_campaign_update_campaign($cid, $update = TRUE) {
  $mcapi = mailchimp_get_api_object();

  $record = array(
    'cid' => $cid,
    'update_time' => REQUEST_TIME,
  );

  // Request all datas from the campaign.
  $campaign = $mcapi->campaigns(array('campaign_id' => $cid));

  if ($mcapi->errorCode) {
    // Diplay and log error if any.
    $message = t('Some error has occured while get datas from MailChimp. Please visit the <em>!mcadmin</em>!', array('!mcadmin' => _mailchimp_campaign_mailchimp_admin_link(t('Campaigns admin page'), 'campaigns/'))) . ' ' . _mailchimp_campaign_mcapi_error_message($mcapi);

    drupal_set_message($message, 'error');
    watchdog('mailchimp_campaign', $message, array(), WATCHDOG_ERROR);
  }
  else {
    $record['data'] = serialize($campaign['data'][0]);

    if ($update) {
      // Update record.
      drupal_write_record('mailchimp_campaign_node_campaigns', $record, array('cid'));

      $message = t('<em>!title</em> campaign datas was updated.', array('!title' => $campaign['data'][0]['title']));

      drupal_set_message($message);
      watchdog('mailchimp_campaign', $message);
    }
  }

  return $record;
}

/**
 * Send MailChimp campaign.
 */
function mailchimp_campaign_send($cid) {
  $mcapi = mailchimp_get_api_object();

  // Send campaign.
  $sent = $mcapi->campaignSendNow($cid);

  if ($mcapi->errorCode) {
    // Display and log error, if any.
    $message = t('MailChimp error. The campaign was not sent, campaign Id: <em>!cid</em>.', array('!cid' => $cid)) . ' ' . _mailchimp_campaign_mcapi_error_message($mcapi);

    drupal_set_message($message, 'error');
    watchdog('mailchimp_campaign', $message, array(), WATCHDOG_ERROR);
  }
  else {
    // Update campaign details in the database.
    mailchimp_campaign_update_campaign($cid);

    $message = t('MailChimp campaign was sent, campaign Id: <em>!cid</em>.', array('!cid' => $cid));

    drupal_set_message($message);
    watchdog('mailchimp_campaign', $message);
  }
}

/**
 * Delete a campaign from MailChimp.
 */
function mailchimp_campaign_delete_campaign($cid) {
  $mcapi = mailchimp_get_api_object();

  // Delete campaign
  $delete = $mcapi->campaignDelete($cid);

  if ($mcapi->errorCode) {
    // Display and log error, if any.
    $message = t('MailChimp error. The campaign was not deleted, campaign ID: <em>!cid</em>.', array('!cid' => $cid)) . ' ' . _mailchimp_campaign_mcapi_error_message($mcapi);

    drupal_set_message($message, 'error');
  }
  else {
    // Delete campaign from the database
    _mailchimp_campaign_delete_form_database($cid);

    $message = t('MailChimp campaign was deleted from MailChimp, campaign ID: <em>!cid</em>.', array('!cid' => $cid));

    drupal_set_message($message);
    watchdog('mailchimp_campaign', $message);
  }
}

/**
 * Get url or link to MaliChimp admin pages.
 */
function _mailchimp_campaign_mailchimp_admin_link($text = '', $path = '', $web_id = '', $return_url = FALSE) {
  $key = variable_get('mailchimp_api_key', FALSE);
  if ($key) {
    $dc = explode('-', $key, 2);
    $url = 'https://' . $dc[1] . '.admin.mailchimp.com/';

    if ($path) {
      $url .= $path;
    }
    if ($web_id) {
      $url .= '?id=' . $web_id;
    }

    if ($return_url) {
      return $url;
    }
    elseif ($text) {
      return l($text, $url, array('attributes' => array('target' => '_blank')));
    }
  }

  return FALSE;
}

/**
 * Returns translatable error message text, with MailChimp error.
 */
function _mailchimp_campaign_mcapi_error_message($mcapi) {
  return t('MailChimp error code: <em>!errorCode</em>, MailChimp error message: <em>!errorMessage</em>.', array('!errorCode' => $mcapi->errorCode, '!errorMessage' => $mcapi->errorMessage));
}

/**
 * Returns an array of mailing lists, for option values.
 */
function _mailchimp_campaign_lists_options() {
  $lists = mailchimp_get_lists();

  $options = array('' => t('-- Select --'));
  foreach ($lists as $list) {
    $options[$list['id']] = $list['name'];
  }

  return $options;
}

/**
 * Return a MailChimp mailing list name.
 */
function _mailchimp_campaign_list_name($list_id) {
  $lists = mailchimp_get_lists();

  return $lists[$list_id]['name'];
}

/**
 * Change the relative URLs to absolute ones in the message.
 */
function _mailchimp_campaign_convert_url($text) {
  global $base_url;
  $matches = array();
  preg_match_all('/<(a|img).*?(href|src)="(.*?)"/', $text, $matches);
  foreach ($matches[3] as $key => $url) {
    if ($url[0] == '/') {
      $new_url = $base_url . $url;
      $new_match = str_replace($url, $new_url, $matches[0][$key]);
      $text = str_replace($matches[0][$key], $new_match, $text);
    }
  }

  return $text;
}

/**
 * Delete a campaign from the database.
 */
function _mailchimp_campaign_delete_form_database($cid) {
  $delete = db_delete('mailchimp_campaign_node_campaigns')
    ->condition('cid', $cid)
    ->execute();

  if ($delete) {
    $message = t('MailChimp campaign was deleted from database, campaign ID: <em>!cid</em>.', array('!cid' => $cid));
    drupal_set_message($message);
    watchdog('mailchimp_campaign', $message);
  }
  else {
    $message = t('Some error has occured. The campaign was not deleted from the database.');
    drupal_set_message($message, 'error');
  }
}

/**
 * Returns campaign content of a node.
 */
function _mailchimp_campaign_body($node) {
  $render = node_view($node, 'mailchimp_campaign');
  $content = drupal_render($render);
  return _mailchimp_campaign_convert_url($content);
}

/**
 * Node preprocess for campaigns.
 */
function mailchimp_campaign_preprocess_node(&$variables) {
  if ($variables['view_mode'] == 'mailchimp_campaign') {
    $variables['theme_hook_suggestions'][] = 'node__mailchimp_campaign';
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function mailchimp_campaign_theme_registry_alter(&$theme_registry) {
  if (!isset($theme_registry['node__mailchimp_campaign'])) {
    $theme_registry['node__mailchimp_campaign']['template'] = drupal_get_path('module', 'mailchimp_campaign') . '/node--mailchimp-campaign';
    $theme_registry['node__mailchimp_campaign']['type'] = 'module';
    $theme_registry['node__mailchimp_campaign']['theme path'] = drupal_get_path('module', 'mailchimp_campaign');
  }
}
